version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: finance-hub-backend
    env_file:
      - ./backend/.env
    ports:
      - "3000:3000"
    networks:
      - finance-network
    restart: unless-stopped

  web:
    build:
      context: ./web
    container_name: finance-hub-web
    env_file:
      - ./web/.env
    depends_on:
      - backend
    ports:
      - "3001:3001"
    networks:
      - finance-network
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    restart: unless-stopped

networks:
  finance-network:
    driver: bridge
